apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: cloudforge
data:
  SPRING_DATA_MONGODB_URI: "mongodb://root:password@mongodb.cloudforge.svc.cluster.local:27017/product-service?authSource=admin"
