apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: NodePort
  selector:
    app: inventory-service
    version: blue 
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082

