apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  namespace: cloudforge
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.cloudforge.svc.cluster.local:3306/inventory_service"
