apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: raslenmissaoui061/orderservice
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: order-service-config
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: inventory-service-config
            - name: LOKI_URL
              value: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push" 
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://tempo.test.svc.cluster.local:9411"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service.test.svc.cluster.local:8080"
            - name: ORDER_SERVICE_URL
              value: "http://order-service.test.svc.cluster.local:8081"
            - name: INVENTORY_SERVICE_URL
              value: "http://inventory-service.test.svc.cluster.local:8082"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "broker.test.svc.cluster.local:29092"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.test.svc.cluster.local:3306/order_service"

