apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
      color: green
  template:
    metadata:
      labels:
        app: product-service
        color: green
    spec:
      containers:
        - name: product-service
          image: raslenmissaoui061/product-service
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATA_MONGODB_URI
                  name: product-service-config
            - name: LOKI_URL
              value: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://tempo.monitoring.svc.cluster.local:9411"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service.cloudforge.svc.cluster.local:8080"
            - name: ORDER_SERVICE_URL
              value: "http://order-service.cloudforge.svc.cluster.local:8081"
            - name: INVENTORY_SERVICE_URL
              value: "http://inventory-service.cloudforge.svc.cluster.local:8082"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "broker.cloudforge.svc.cluster.local:29092"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: cloudforge
data:
  SPRING_DATA_MONGODB_URI: "mongodb://root:password@mongodb.cloudforge.svc.cluster.local:27017/product-service?authSource=admin"








        
