apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
      version: blue
  template:
    metadata:
      labels:
        app: inventory-service
        version: blue
    spec:
      containers:
        - name: inventory-service
          image: raslenmissaoui061/inventoryservice
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: inventory-service-config
            - name: LOKI_URL
              value: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://tempo.monitoring.svc.cluster.local:9411"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service.cloudforge.svc.cluster.local:8080"
            - name: ORDER_SERVICE_URL
              value: "http://order-service.cloudforge.svc.cluster.local:8081"
            - name: INVENTORY_SERVICE_URL
              value: "http://inventory-service.cloudforge.svc.cluster.local:8082"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "broker.cloudforge.svc.cluster.local:29092"
---


apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  namespace: cloudforge
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.cloudforge.svc.cluster.local:3306/inventory_service"
