apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: NodePort
  selector:
    app: inventory-service
    version: blue 
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082

---

# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.test.svc.cluster.local:3306/inventory_service"
